name: "Setup Terraform"
description: "Checkout and set up Terraform"
runs:
  using: "composite"
  steps:
    - name: Setup aqua
      uses: ./.github/actions/aqua_setup

    - name: Set up GCP credentials
      run: |
        echo $GCP_SA | base64 -d | jq > gcloud.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcloud.json" >> $GITHUB_ENV
      shell: bash

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${BUCKET_NAME}"
      shell: bash
