# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      TF_VAR_KUBE_CLIENT_CERT: ${{ secrets.TF_VAR_KUBE_CLIENT_CERT }}
      TF_VAR_KUBE_CLIENT_KEY: ${{ secrets.TF_VAR_KUBE_CLIENT_KEY }}
      TF_VAR_KUBE_CLUSTER_CA_CERT: ${{ secrets.TF_VAR_KUBE_CLUSTER_CA_CERT }}
      TF_VAR_KUBE_HOST: ${{ secrets.TF_VAR_KUBE_HOST }}
      GITHUB_TOKEN: ${{ secrets.TFCMT_GITHUB_TOKEN }}
      TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: ./.github/actions/terraform_init

      - name: Minimize resolved terraform notifications
        run: github-comment hide

      - name: Set tfcmt env
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            echo "PR_NUMBER=5" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
        run: tfcmt apply -- terraform apply -auto-approve
