# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Terraform Plan"
on:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - name: Setup aqua tools
        run: |
          aqua i -l

      - name: tflint
        run: |
          tflint --init
          tflint

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup aqua
        uses: ./.github/actions/aqua_setup
      - name: trivy
        run: |
          trivy config ./

  fmt:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}

    steps:
      # - uses: .github/workflows/terraform_init.yml

      - name: Terraform fmt
        run: terraform fmt

  plan:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}

    steps:
      # - uses: .github/workflows/terraform_init.yml

      - name: Terraform Plan
        run: terraform plan
