# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Terraform Apply"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.4"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 456.0.0"

      - name: Set up Google Cloud
        run: |
          echo $GCP_SA | base64 -d | jq > gcloud.json
          gcloud auth activate-service-account --key-file=gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=gcloud.json" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${BUCKET_NAME}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
