# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Terraform Plan"
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.4"

      - name: Set up Google Cloud
        run: |
          echo "$GOOGLE_CREDENTIALS" > gcloud.json
          gcloud auth activate-service-account --key-file=gcloud.json

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${BUCKET_NAME}"

      - name: Terraform Plan
        run: terraform plan
