# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "test"
on:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup aqua
        uses: ./.github/actions/aqua_setup

      - name: tflint
        run: |
          tflint --init
          tflint

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup aqua
        uses: ./.github/actions/aqua_setup

      - name: trivy
        run: |
          trivy config ./

  fmt:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: ./.github/actions/terraform_init

      - name: Terraform fmt
        run: terraform fmt

  plan:
    runs-on: ubuntu-latest

    env:
      GCP_SA: ${{ secrets.GCP_SA }}
      BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}

    steps:
      - name: env test
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "$OWNER"
          echo "$REPO"
          echo "$PR_NUMBER"
          exit 1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: ./.github/actions/terraform_init

      - name: Setup aqua
        uses: ./.github/actions/aqua_setup

      - name: Terraform Plan
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          PR_NUMBER=${{ github.event.pull_request.number }}
          tfcmt -owner "$OWNER" -repo "$REPO" -pr "$PR_NUMBER" plan -- terraform plan
